[package]
name = "libfabric"
version = "0.1.0"
edition = "2021"


[dependencies]
libfabric-sys = { path = "../libfabric-sys" }
debug_print = "1.0.0"
tokio = { version = "1.38", optional = true, features = [
    "net",
    "rt",
    "macros",
] }
async-std = { version = "1.12.0", optional = true }
async-io = { version = "2.3.2", optional = true }
parking_lot = { version = "0.12.1", optional = true }
[features]
# default = ["thread-safe"]
# default = ["use-async-std"]
use-async-std = ["async-std", "async-io"]
use-tokio = ["tokio"]
thread-safe = ["parking_lot"]
