[package]
name = "libfabric"
version = "0.1.0"
edition = "2021"


[dependencies]
libfabric-sys = { path = "../libfabric-sys" }
debug_print = "1.0.0"
async-std = {version = "1.12.0"}


# [features]
# async = ["async-std"]